package dao;
import java.math.BigDecimal;import java.sql.*;import java.util.*;import mylib.DBUtils;
public class AdminLoyaltyDAO{
 public Map<String,String> configs()throws Exception{Map<String,String> m=new LinkedHashMap<>();try(Connection c=DBUtils.getConnection();PreparedStatement p=c.prepareStatement("SELECT config_key,config_value FROM LoyaltyConfig ORDER BY config_key");ResultSet r=p.executeQuery()){while(r.next())m.put(r.getString(1),r.getString(2));}return m;}
 public List<Map<String,Object>> tiers()throws Exception{return rows("SELECT * FROM MembershipTier ORDER BY tier_order");}
 public List<Map<String,Object>> rewards()throws Exception{return rows("SELECT * FROM Reward ORDER BY required_points");}
 private List<Map<String,Object>> rows(String sql)throws Exception{List<Map<String,Object>> a=new ArrayList<>();try(Connection c=DBUtils.getConnection();PreparedStatement p=c.prepareStatement(sql);ResultSet r=p.executeQuery()){ResultSetMetaData md=r.getMetaData();while(r.next()){Map<String,Object> m=new LinkedHashMap<>();for(int i=1;i<=md.getColumnCount();i++)m.put(md.getColumnLabel(i),r.getObject(i));a.add(m);}}return a;}
 public void saveConfigs(int admin,String expiry,String rate,String days)throws Exception{int e=positive(expiry),r=positive(rate),d=positive(days);try(Connection c=DBUtils.getConnection()){c.setAutoCommit(false);try{upsert(c,"POINT_EXPIRY_MONTHS",String.valueOf(e),admin);upsert(c,"POINT_CONVERSION_RATE",String.valueOf(r),admin);upsert(c,"DEFAULT_VOUCHER_VALIDITY_DAYS",String.valueOf(d),admin);c.commit();}catch(Exception x){c.rollback();throw x;}}}
 private void upsert(Connection c,String k,String v,int admin)throws SQLException{try(PreparedStatement p=c.prepareStatement("UPDATE LoyaltyConfig SET config_value=?,updated_at=GETDATE(),updated_by=? WHERE config_key=?; IF @@ROWCOUNT=0 INSERT LoyaltyConfig(config_key,config_value,updated_by) VALUES(?,?,?)")){p.setString(1,v);p.setInt(2,admin);p.setString(3,k);p.setString(4,k);p.setString(5,v);p.setInt(6,admin);p.executeUpdate();}}
 public void saveReward(Integer id,String name,int points,String type,BigDecimal value,Integer service,int days,BigDecimal max,boolean active)throws Exception{if(name==null||name.trim().isEmpty()||points<=0||days<=0||value.signum()<0||("PERCENT_DISCOUNT".equals(type)&&value.compareTo(new BigDecimal("100"))>0))throw new IllegalArgumentException("Invalid reward data");String sql=id==null?"INSERT Reward(reward_name,required_points,description,reward_type,reward_value,target_service_id,valid_days,maximum_discount,is_active) VALUES(?,?,NULL,?,?,?,?,?,?)":"UPDATE Reward SET reward_name=?,required_points=?,reward_type=?,reward_value=?,target_service_id=?,valid_days=?,maximum_discount=?,is_active=? WHERE reward_id=?";try(Connection c=DBUtils.getConnection();PreparedStatement p=c.prepareStatement(sql)){p.setString(1,name.trim());p.setInt(2,points);p.setString(3,type);p.setBigDecimal(4,value);if(service==null)p.setNull(5,Types.INTEGER);else p.setInt(5,service);p.setInt(6,days);if(max==null)p.setNull(7,Types.DECIMAL);else p.setBigDecimal(7,max);p.setBoolean(8,active);if(id!=null)p.setInt(9,id);p.executeUpdate();}}
 public void saveTier(int id,String name,int minPoints,BigDecimal discount,int priority,String benefits,boolean active)throws Exception{if(name==null||name.trim().isEmpty()||minPoints<0||discount.signum()<0||discount.compareTo(new BigDecimal("100"))>0||priority<0)throw new IllegalArgumentException("Invalid tier data");try(Connection c=DBUtils.getConnection()){c.setAutoCommit(false);try(PreparedStatement x=c.prepareStatement("SELECT COUNT(*) FROM MembershipTier WHERE min_points=? AND tier_id<>?")){x.setInt(1,minPoints);x.setInt(2,id);try(ResultSet r=x.executeQuery()){r.next();if(r.getInt(1)>0)throw new IllegalArgumentException("Tier threshold already exists");}}try(PreparedStatement p=c.prepareStatement("UPDATE MembershipTier SET tier_name=?,min_points=?,discount_percent=?,priority_score=?,benefits=?,is_active=? WHERE tier_id=?")){p.setString(1,name.trim());p.setInt(2,minPoints);p.setBigDecimal(3,discount);p.setInt(4,priority);p.setString(5,benefits);p.setBoolean(6,active);p.setInt(7,id);p.executeUpdate();}c.commit();}}
 private int positive(String v){int n=Integer.parseInt(v);if(n<=0)throw new IllegalArgumentException("Configuration values must be positive");return n;}
}
