name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Download CopyLibs
      run: |
        mkdir -p ./lib-extra
        wget https://repo.maven.apache.org/maven2/org/netbeans/modules/org-netbeans-modules-java-j2seproject-copylibstask/1.0/org-netbeans-modules-java-j2seproject-copylibstask-1.0.jar -O ./lib-extra/org-netbeans-modules-java-j2seproject-copylibstask.jar

    - name: Set CopyLibs path
      run: |
        echo "libs.CopyLibs.classpath=$GITHUB_WORKSPACE/lib-extra/org-netbeans-modules-java-j2seproject-copylibstask.jar" >> AutoWashPro-Website/nbproject/project.properties

    - name: Build with Ant
      run: ant -f AutoWashPro-Website/build.xml
